// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SystemInformation struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Manufacturer         string   `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ProductName          string   `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	SerialNumber         string   `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	SkuNumber            string   `protobuf:"bytes,6,opt,name=sku_number,json=skuNumber,proto3" json:"sku_number,omitempty"`
	Family               string   `protobuf:"bytes,7,opt,name=family,proto3" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInformation) Reset()         { *m = SystemInformation{} }
func (m *SystemInformation) String() string { return proto.CompactTextString(m) }
func (*SystemInformation) ProtoMessage()    {}
func (*SystemInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *SystemInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInformation.Unmarshal(m, b)
}

func (m *SystemInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInformation.Marshal(b, m, deterministic)
}

func (m *SystemInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInformation.Merge(m, src)
}

func (m *SystemInformation) XXX_Size() int {
	return xxx_messageInfo_SystemInformation.Size(m)
}

func (m *SystemInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInformation.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInformation proto.InternalMessageInfo

func (m *SystemInformation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SystemInformation) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *SystemInformation) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *SystemInformation) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SystemInformation) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *SystemInformation) GetSkuNumber() string {
	if m != nil {
		return m.SkuNumber
	}
	return ""
}

func (m *SystemInformation) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

type CPU struct {
	Manufacturer         string   `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPU) Reset()         { *m = CPU{} }
func (m *CPU) String() string { return proto.CompactTextString(m) }
func (*CPU) ProtoMessage()    {}
func (*CPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPU.Unmarshal(m, b)
}

func (m *CPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPU.Marshal(b, m, deterministic)
}

func (m *CPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPU.Merge(m, src)
}

func (m *CPU) XXX_Size() int {
	return xxx_messageInfo_CPU.Size(m)
}

func (m *CPU) XXX_DiscardUnknown() {
	xxx_messageInfo_CPU.DiscardUnknown(m)
}

var xxx_messageInfo_CPU proto.InternalMessageInfo

func (m *CPU) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *CPU) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CreateServerRequest struct {
	SystemInformation    *SystemInformation `protobuf:"bytes,1,opt,name=system_information,json=systemInformation,proto3" json:"system_information,omitempty"`
	Cpu                  *CPU               `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Hostname             string             `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateServerRequest) Reset()         { *m = CreateServerRequest{} }
func (m *CreateServerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServerRequest) ProtoMessage()    {}
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CreateServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServerRequest.Unmarshal(m, b)
}

func (m *CreateServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServerRequest.Marshal(b, m, deterministic)
}

func (m *CreateServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServerRequest.Merge(m, src)
}

func (m *CreateServerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServerRequest.Size(m)
}

func (m *CreateServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServerRequest proto.InternalMessageInfo

func (m *CreateServerRequest) GetSystemInformation() *SystemInformation {
	if m != nil {
		return m.SystemInformation
	}
	return nil
}

func (m *CreateServerRequest) GetCpu() *CPU {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *CreateServerRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type CreateServerResponse struct {
	Wipe                 bool     `protobuf:"varint,1,opt,name=wipe,proto3" json:"wipe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServerResponse) Reset()         { *m = CreateServerResponse{} }
func (m *CreateServerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServerResponse) ProtoMessage()    {}
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CreateServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServerResponse.Unmarshal(m, b)
}

func (m *CreateServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServerResponse.Marshal(b, m, deterministic)
}

func (m *CreateServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServerResponse.Merge(m, src)
}

func (m *CreateServerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServerResponse.Size(m)
}

func (m *CreateServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServerResponse proto.InternalMessageInfo

func (m *CreateServerResponse) GetWipe() bool {
	if m != nil {
		return m.Wipe
	}
	return false
}

type MarkServerAsWipedRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkServerAsWipedRequest) Reset()         { *m = MarkServerAsWipedRequest{} }
func (m *MarkServerAsWipedRequest) String() string { return proto.CompactTextString(m) }
func (*MarkServerAsWipedRequest) ProtoMessage()    {}
func (*MarkServerAsWipedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *MarkServerAsWipedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkServerAsWipedRequest.Unmarshal(m, b)
}

func (m *MarkServerAsWipedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkServerAsWipedRequest.Marshal(b, m, deterministic)
}

func (m *MarkServerAsWipedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkServerAsWipedRequest.Merge(m, src)
}

func (m *MarkServerAsWipedRequest) XXX_Size() int {
	return xxx_messageInfo_MarkServerAsWipedRequest.Size(m)
}

func (m *MarkServerAsWipedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkServerAsWipedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkServerAsWipedRequest proto.InternalMessageInfo

func (m *MarkServerAsWipedRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type MarkServerAsWipedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkServerAsWipedResponse) Reset()         { *m = MarkServerAsWipedResponse{} }
func (m *MarkServerAsWipedResponse) String() string { return proto.CompactTextString(m) }
func (*MarkServerAsWipedResponse) ProtoMessage()    {}
func (*MarkServerAsWipedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *MarkServerAsWipedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkServerAsWipedResponse.Unmarshal(m, b)
}

func (m *MarkServerAsWipedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkServerAsWipedResponse.Marshal(b, m, deterministic)
}

func (m *MarkServerAsWipedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkServerAsWipedResponse.Merge(m, src)
}

func (m *MarkServerAsWipedResponse) XXX_Size() int {
	return xxx_messageInfo_MarkServerAsWipedResponse.Size(m)
}

func (m *MarkServerAsWipedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkServerAsWipedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MarkServerAsWipedResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SystemInformation)(nil), "api.SystemInformation")
	proto.RegisterType((*CPU)(nil), "api.CPU")
	proto.RegisterType((*CreateServerRequest)(nil), "api.CreateServerRequest")
	proto.RegisterType((*CreateServerResponse)(nil), "api.CreateServerResponse")
	proto.RegisterType((*MarkServerAsWipedRequest)(nil), "api.MarkServerAsWipedRequest")
	proto.RegisterType((*MarkServerAsWipedResponse)(nil), "api.MarkServerAsWipedResponse")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdd, 0x6a, 0x13, 0x41,
	0x18, 0x65, 0x9b, 0x36, 0x4d, 0xbe, 0xc4, 0x8b, 0x8c, 0x52, 0xa6, 0x91, 0x8a, 0xae, 0x37, 0x22,
	0x24, 0x0b, 0xf1, 0x09, 0xea, 0xe2, 0x45, 0x11, 0x4b, 0xd9, 0x52, 0x04, 0x6f, 0xc2, 0x97, 0xcd,
	0x97, 0x74, 0xc8, 0xce, 0x8f, 0xf3, 0x53, 0xe9, 0x7b, 0xf8, 0x00, 0x3e, 0x9c, 0x0f, 0x22, 0x99,
	0x4d, 0x6c, 0xc2, 0xa6, 0x77, 0xf3, 0x9d, 0x73, 0x76, 0xce, 0xf9, 0xce, 0xb0, 0xd0, 0x45, 0x23,
	0xc6, 0xc6, 0x6a, 0xaf, 0x59, 0x0b, 0x8d, 0x48, 0xff, 0x26, 0x30, 0xb8, 0x7d, 0x74, 0x9e, 0xe4,
	0x95, 0x5a, 0x68, 0x2b, 0xd1, 0x0b, 0xad, 0x18, 0x83, 0xe3, 0x10, 0xc4, 0x9c, 0x27, 0x6f, 0x93,
	0x0f, 0xdd, 0x22, 0x9e, 0x59, 0x0a, 0x7d, 0x89, 0x2a, 0x2c, 0xb0, 0xf4, 0xc1, 0x92, 0xe5, 0x47,
	0x91, 0xdb, 0xc3, 0xd8, 0x3b, 0xe8, 0x1b, 0xab, 0xe7, 0xa1, 0xf4, 0x53, 0x85, 0x92, 0x78, 0x2b,
	0x6a, 0x7a, 0x1b, 0xec, 0x1a, 0x25, 0x31, 0x0e, 0xa7, 0x0f, 0x64, 0x9d, 0xd0, 0x8a, 0x1f, 0x47,
	0x76, 0x3b, 0xb2, 0xf7, 0xf0, 0xc2, 0x91, 0x15, 0x58, 0x4d, 0x55, 0x90, 0x33, 0xb2, 0xfc, 0xa4,
	0x76, 0xa8, 0xc1, 0xeb, 0x88, 0xb1, 0x0b, 0x00, 0xb7, 0x0a, 0x5b, 0x45, 0x3b, 0x2a, 0xba, 0x6e,
	0x15, 0x36, 0xf4, 0x19, 0xb4, 0x17, 0x28, 0x45, 0xf5, 0xc8, 0x4f, 0x23, 0xb5, 0x99, 0xd2, 0x1c,
	0x5a, 0xf9, 0xcd, 0x5d, 0x63, 0x87, 0xe4, 0xc0, 0x0e, 0x3b, 0x01, 0x8f, 0xf6, 0x02, 0xa6, 0xbf,
	0x13, 0x78, 0x99, 0x5b, 0x42, 0x4f, 0xb7, 0x64, 0x1f, 0xc8, 0x16, 0xf4, 0x33, 0x90, 0xf3, 0xec,
	0x0b, 0x30, 0x17, 0x2b, 0x9c, 0x8a, 0xa7, 0x0e, 0xe3, 0xdd, 0xbd, 0xc9, 0xd9, 0x78, 0x5d, 0x78,
	0xa3, 0xe1, 0x62, 0xe0, 0x1a, 0xa5, 0x0f, 0xa1, 0x55, 0x9a, 0x10, 0x4d, 0x7b, 0x93, 0x4e, 0xfc,
	0x2e, 0xbf, 0xb9, 0x2b, 0xd6, 0x20, 0x1b, 0x42, 0xe7, 0x5e, 0x3b, 0xbf, 0x53, 0xea, 0xff, 0x39,
	0xfd, 0x08, 0xaf, 0xf6, 0x53, 0x39, 0xa3, 0x95, 0xa3, 0xf5, 0x23, 0xfe, 0x12, 0x86, 0x62, 0x90,
	0x4e, 0x11, 0xcf, 0xe9, 0x18, 0xf8, 0x37, 0xb4, 0xab, 0x5a, 0x79, 0xe9, 0xbe, 0x0b, 0x43, 0xf3,
	0xed, 0x1a, 0x07, 0x1e, 0x3d, 0x7d, 0x0d, 0xe7, 0x07, 0xf4, 0xb5, 0xc1, 0xe4, 0x4f, 0x02, 0x27,
	0x97, 0x4b, 0x52, 0x9e, 0xe5, 0xd0, 0xdf, 0x8d, 0xc0, 0x78, 0x9d, 0xbe, 0xd9, 0xd5, 0xf0, 0xfc,
	0x00, 0xb3, 0xc9, 0x5b, 0xc0, 0xa0, 0xe1, 0xc5, 0x2e, 0xa2, 0xfe, 0xb9, 0xcc, 0xc3, 0x37, 0xcf,
	0xd1, 0xf5, 0x9d, 0x9f, 0xbf, 0xfe, 0xb8, 0x5a, 0x0a, 0x7f, 0x1f, 0x66, 0xe3, 0x52, 0xcb, 0xcc,
	0x63, 0xa5, 0xdd, 0xa8, 0x6e, 0xde, 0x65, 0x4e, 0xcc, 0xc9, 0xea, 0x0c, 0x8d, 0xc9, 0x24, 0x79,
	0xac, 0x46, 0xa5, 0x56, 0xde, 0xea, 0xaa, 0x22, 0x3b, 0x92, 0xa8, 0x70, 0x49, 0x36, 0x13, 0xca,
	0x93, 0x55, 0x58, 0x65, 0x68, 0xc4, 0xac, 0x1d, 0xff, 0x9b, 0x4f, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0xd7, 0xbd, 0x36, 0x44, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConnInterface
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error)
	MarkServerAsWiped(ctx context.Context, in *MarkServerAsWipedRequest, opts ...grpc.CallOption) (*MarkServerAsWipedResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error) {
	out := new(CreateServerResponse)
	err := c.cc.Invoke(ctx, "/api.Agent/CreateServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) MarkServerAsWiped(ctx context.Context, in *MarkServerAsWipedRequest, opts ...grpc.CallOption) (*MarkServerAsWipedResponse, error) {
	out := new(MarkServerAsWipedResponse)
	err := c.cc.Invoke(ctx, "/api.Agent/MarkServerAsWiped", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error)
	MarkServerAsWiped(context.Context, *MarkServerAsWipedRequest) (*MarkServerAsWipedResponse, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) CreateServer(ctx context.Context, req *CreateServerRequest) (*CreateServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServer not implemented")
}

func (*UnimplementedAgentServer) MarkServerAsWiped(ctx context.Context, req *MarkServerAsWipedRequest) (*MarkServerAsWipedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkServerAsWiped not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Agent/CreateServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_MarkServerAsWiped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkServerAsWipedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).MarkServerAsWiped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Agent/MarkServerAsWiped",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).MarkServerAsWiped(ctx, req.(*MarkServerAsWipedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServer",
			Handler:    _Agent_CreateServer_Handler,
		},
		{
			MethodName: "MarkServerAsWiped",
			Handler:    _Agent_MarkServerAsWiped_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
