// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SystemInformation struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Manufacturer         string   `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ProductName          string   `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	SerialNumber         string   `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	SkuNumber            string   `protobuf:"bytes,6,opt,name=sku_number,json=skuNumber,proto3" json:"sku_number,omitempty"`
	Family               string   `protobuf:"bytes,7,opt,name=family,proto3" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInformation) Reset()         { *m = SystemInformation{} }
func (m *SystemInformation) String() string { return proto.CompactTextString(m) }
func (*SystemInformation) ProtoMessage()    {}
func (*SystemInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0}
}

func (m *SystemInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInformation.Unmarshal(m, b)
}

func (m *SystemInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInformation.Marshal(b, m, deterministic)
}

func (m *SystemInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInformation.Merge(m, src)
}

func (m *SystemInformation) XXX_Size() int {
	return xxx_messageInfo_SystemInformation.Size(m)
}

func (m *SystemInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInformation.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInformation proto.InternalMessageInfo

func (m *SystemInformation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SystemInformation) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *SystemInformation) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *SystemInformation) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SystemInformation) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *SystemInformation) GetSkuNumber() string {
	if m != nil {
		return m.SkuNumber
	}
	return ""
}

func (m *SystemInformation) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

type CPU struct {
	Manufacturer         string   `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPU) Reset()         { *m = CPU{} }
func (m *CPU) String() string { return proto.CompactTextString(m) }
func (*CPU) ProtoMessage()    {}
func (*CPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1}
}

func (m *CPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPU.Unmarshal(m, b)
}

func (m *CPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPU.Marshal(b, m, deterministic)
}

func (m *CPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPU.Merge(m, src)
}

func (m *CPU) XXX_Size() int {
	return xxx_messageInfo_CPU.Size(m)
}

func (m *CPU) XXX_DiscardUnknown() {
	xxx_messageInfo_CPU.DiscardUnknown(m)
}

var xxx_messageInfo_CPU proto.InternalMessageInfo

func (m *CPU) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *CPU) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CreateServerRequest struct {
	SystemInformation    *SystemInformation `protobuf:"bytes,1,opt,name=system_information,json=systemInformation,proto3" json:"system_information,omitempty"`
	Cpu                  *CPU               `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Hostname             string             `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateServerRequest) Reset()         { *m = CreateServerRequest{} }
func (m *CreateServerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServerRequest) ProtoMessage()    {}
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{2}
}

func (m *CreateServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServerRequest.Unmarshal(m, b)
}

func (m *CreateServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServerRequest.Marshal(b, m, deterministic)
}

func (m *CreateServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServerRequest.Merge(m, src)
}

func (m *CreateServerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServerRequest.Size(m)
}

func (m *CreateServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServerRequest proto.InternalMessageInfo

func (m *CreateServerRequest) GetSystemInformation() *SystemInformation {
	if m != nil {
		return m.SystemInformation
	}
	return nil
}

func (m *CreateServerRequest) GetCpu() *CPU {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *CreateServerRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type CreateServerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServerResponse) Reset()         { *m = CreateServerResponse{} }
func (m *CreateServerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServerResponse) ProtoMessage()    {}
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{3}
}

func (m *CreateServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServerResponse.Unmarshal(m, b)
}

func (m *CreateServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServerResponse.Marshal(b, m, deterministic)
}

func (m *CreateServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServerResponse.Merge(m, src)
}

func (m *CreateServerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServerResponse.Size(m)
}

func (m *CreateServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SystemInformation)(nil), "api.SystemInformation")
	proto.RegisterType((*CPU)(nil), "api.CPU")
	proto.RegisterType((*CreateServerRequest)(nil), "api.CreateServerRequest")
	proto.RegisterType((*CreateServerResponse)(nil), "api.CreateServerResponse")
}

func init() {
	proto.RegisterFile("discovery.proto", fileDescriptor_1e7ff60feb39c8d0)
}

var fileDescriptor_1e7ff60feb39c8d0 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xd5, 0x36, 0x25, 0x6d, 0x26, 0x41, 0xa8, 0x06, 0x45, 0x26, 0x12, 0x12, 0x2c, 0x17, 0x2e,
	0xc9, 0x4a, 0xe1, 0x1f, 0xb0, 0x70, 0xa8, 0x90, 0xaa, 0x28, 0x55, 0x2f, 0x5c, 0xa2, 0xc9, 0xee,
	0xa4, 0xb5, 0xba, 0xfe, 0x60, 0x6c, 0x47, 0xca, 0xff, 0xe0, 0x27, 0xf2, 0x43, 0x10, 0xde, 0x04,
	0x12, 0x6d, 0x6e, 0x9e, 0xf7, 0x9e, 0x67, 0xe6, 0x3d, 0x1b, 0x5e, 0xd5, 0xca, 0x57, 0x76, 0x4b,
	0xbc, 0x9b, 0x39, 0xb6, 0xc1, 0x8a, 0x1e, 0x3a, 0x95, 0xff, 0xce, 0xe0, 0xe6, 0x7e, 0xe7, 0x03,
	0xe9, 0x5b, 0xb3, 0xb1, 0xac, 0x31, 0x28, 0x6b, 0x84, 0x80, 0xcb, 0x18, 0x55, 0x2d, 0xb3, 0xf7,
	0xd9, 0xa7, 0xc1, 0x32, 0x9d, 0x45, 0x0e, 0x23, 0x8d, 0x26, 0x6e, 0xb0, 0x0a, 0x91, 0x89, 0xe5,
	0x45, 0xe2, 0x4e, 0x30, 0xf1, 0x01, 0x46, 0x8e, 0x6d, 0x1d, 0xab, 0xb0, 0x32, 0xa8, 0x49, 0xf6,
	0x92, 0x66, 0xb8, 0xc7, 0xee, 0x50, 0x93, 0x90, 0x70, 0xb5, 0x25, 0xf6, 0xca, 0x1a, 0x79, 0x99,
	0xd8, 0x43, 0x29, 0x3e, 0xc2, 0x4b, 0x4f, 0xac, 0xb0, 0x59, 0x99, 0xa8, 0xd7, 0xc4, 0xf2, 0x45,
	0x3b, 0xa1, 0x05, 0xef, 0x12, 0x26, 0xde, 0x01, 0xf8, 0xe7, 0x78, 0x50, 0xf4, 0x93, 0x62, 0xe0,
	0x9f, 0xe3, 0x9e, 0x1e, 0x43, 0x7f, 0x83, 0x5a, 0x35, 0x3b, 0x79, 0x95, 0xa8, 0x7d, 0x95, 0x97,
	0xd0, 0x2b, 0x17, 0x0f, 0x1d, 0x0f, 0xd9, 0x19, 0x0f, 0x47, 0x0b, 0x5e, 0x9c, 0x2c, 0x98, 0xff,
	0xca, 0xe0, 0x75, 0xc9, 0x84, 0x81, 0xee, 0x89, 0xb7, 0xc4, 0x4b, 0xfa, 0x19, 0xc9, 0x07, 0xf1,
	0x0d, 0x84, 0x4f, 0x11, 0xae, 0xd4, 0xff, 0x0c, 0x53, 0xef, 0xe1, 0x7c, 0x3c, 0x43, 0xa7, 0x66,
	0x9d, 0x84, 0x97, 0x37, 0xbe, 0x13, 0xfa, 0x04, 0x7a, 0x95, 0x8b, 0x69, 0xe8, 0x70, 0x7e, 0x9d,
	0xee, 0x95, 0x8b, 0x87, 0xe5, 0x5f, 0x50, 0x4c, 0xe0, 0xfa, 0xc9, 0xfa, 0x70, 0x14, 0xea, 0xbf,
	0x3a, 0x1f, 0xc3, 0x9b, 0xd3, 0xad, 0xbc, 0xb3, 0xc6, 0xd3, 0x7c, 0x01, 0x83, 0xaf, 0x87, 0x27,
	0x17, 0x25, 0x8c, 0x8e, 0x45, 0x42, 0xb6, 0xfd, 0xbb, 0x6e, 0x26, 0x6f, 0xcf, 0x30, 0x6d, 0xc7,
	0x2f, 0xdf, 0x7f, 0xdc, 0x3e, 0xaa, 0xf0, 0x14, 0xd7, 0xb3, 0xca, 0xea, 0x22, 0x60, 0x63, 0xfd,
	0xb4, 0xf5, 0xe1, 0x0b, 0xaf, 0x6a, 0x62, 0x5b, 0xa0, 0x73, 0x85, 0xa6, 0x80, 0xcd, 0xb4, 0xb2,
	0x26, 0xb0, 0x6d, 0x1a, 0xe2, 0xa9, 0x46, 0x83, 0x8f, 0xc4, 0x85, 0x32, 0x81, 0xd8, 0x60, 0x53,
	0xa0, 0x53, 0xeb, 0x7e, 0xfa, 0x85, 0x9f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x62, 0x8b, 0x2b,
	0x62, 0x98, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConnInterface
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DiscoveryClient is the client API for Discovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscoveryClient interface {
	CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error)
}

type discoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryClient(cc grpc.ClientConnInterface) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error) {
	out := new(CreateServerResponse)
	err := c.cc.Invoke(ctx, "/api.Discovery/CreateServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServer is the server API for Discovery service.
type DiscoveryServer interface {
	CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error)
}

// UnimplementedDiscoveryServer can be embedded to have forward compatible implementations.
type UnimplementedDiscoveryServer struct {
}

func (*UnimplementedDiscoveryServer) CreateServer(ctx context.Context, req *CreateServerRequest) (*CreateServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServer not implemented")
}

func RegisterDiscoveryServer(s *grpc.Server, srv DiscoveryServer) {
	s.RegisterService(&_Discovery_serviceDesc, srv)
}

func _Discovery_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Discovery/CreateServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).CreateServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServer",
			Handler:    _Discovery_CreateServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
