// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageType int32

const (
	StorageType_Unknown StorageType = 0
	StorageType_SSD     StorageType = 1
	StorageType_HDD     StorageType = 2
	StorageType_NVMe    StorageType = 3
	StorageType_SD      StorageType = 4
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "Unknown",
		1: "SSD",
		2: "HDD",
		3: "NVMe",
		4: "SD",
	}
	StorageType_value = map[string]int32{
		"Unknown": 0,
		"SSD":     1,
		"HDD":     2,
		"NVMe":    3,
		"SD":      4,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type BMCInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Pass          string                 `protobuf:"bytes,4,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BMCInfo) Reset() {
	*x = BMCInfo{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMCInfo) ProtoMessage() {}

func (x *BMCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMCInfo.ProtoReflect.Descriptor instead.
func (*BMCInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *BMCInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BMCInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BMCInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BMCInfo) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type SystemInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	SkuNumber     string                 `protobuf:"bytes,6,opt,name=sku_number,json=skuNumber,proto3" json:"sku_number,omitempty"`
	Family        string                 `protobuf:"bytes,7,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInformation) Reset() {
	*x = SystemInformation{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInformation) ProtoMessage() {}

func (x *SystemInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInformation.ProtoReflect.Descriptor instead.
func (*SystemInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInformation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SystemInformation) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *SystemInformation) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SystemInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInformation) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *SystemInformation) GetSkuNumber() string {
	if x != nil {
		return x.SkuNumber
	}
	return ""
}

func (x *SystemInformation) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

type Processor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  string                 `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Speed         uint32                 `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`
	CoreCount     uint32                 `protobuf:"varint,5,opt,name=core_count,json=coreCount,proto3" json:"core_count,omitempty"`
	ThreadCount   uint32                 `protobuf:"varint,6,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Processor) Reset() {
	*x = Processor{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Processor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Processor) ProtoMessage() {}

func (x *Processor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Processor.ProtoReflect.Descriptor instead.
func (*Processor) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Processor) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Processor) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Processor) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Processor) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Processor) GetCoreCount() uint32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

func (x *Processor) GetThreadCount() uint32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

type ComputeInformation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalCoreCount   uint32                 `protobuf:"varint,1,opt,name=total_core_count,json=totalCoreCount,proto3" json:"total_core_count,omitempty"`
	TotalThreadCount uint32                 `protobuf:"varint,2,opt,name=total_thread_count,json=totalThreadCount,proto3" json:"total_thread_count,omitempty"`
	ProcessorCount   uint32                 `protobuf:"varint,3,opt,name=processor_count,json=processorCount,proto3" json:"processor_count,omitempty"`
	Processors       []*Processor           `protobuf:"bytes,4,rep,name=processors,proto3" json:"processors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComputeInformation) Reset() {
	*x = ComputeInformation{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInformation) ProtoMessage() {}

func (x *ComputeInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeInformation.ProtoReflect.Descriptor instead.
func (*ComputeInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *ComputeInformation) GetTotalCoreCount() uint32 {
	if x != nil {
		return x.TotalCoreCount
	}
	return 0
}

func (x *ComputeInformation) GetTotalThreadCount() uint32 {
	if x != nil {
		return x.TotalThreadCount
	}
	return 0
}

func (x *ComputeInformation) GetProcessorCount() uint32 {
	if x != nil {
		return x.ProcessorCount
	}
	return 0
}

func (x *ComputeInformation) GetProcessors() []*Processor {
	if x != nil {
		return x.Processors
	}
	return nil
}

type MemoryModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  string                 `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Size          uint32                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Speed         uint32                 `protobuf:"varint,6,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryModule) Reset() {
	*x = MemoryModule{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryModule) ProtoMessage() {}

func (x *MemoryModule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryModule.ProtoReflect.Descriptor instead.
func (*MemoryModule) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryModule) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *MemoryModule) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *MemoryModule) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *MemoryModule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MemoryModule) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MemoryModule) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type MemoryInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSize     uint32                 `protobuf:"varint,1,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	ModuleCount   uint32                 `protobuf:"varint,2,opt,name=module_count,json=moduleCount,proto3" json:"module_count,omitempty"`
	Modules       []*MemoryModule        `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInformation) Reset() {
	*x = MemoryInformation{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInformation) ProtoMessage() {}

func (x *MemoryInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInformation.ProtoReflect.Descriptor instead.
func (*MemoryInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryInformation) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *MemoryInformation) GetModuleCount() uint32 {
	if x != nil {
		return x.ModuleCount
	}
	return 0
}

func (x *MemoryInformation) GetModules() []*MemoryModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

type StorageDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StorageType            `protobuf:"varint,1,opt,name=type,proto3,enum=api.StorageType" json:"type,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string                 `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	DeviceName    string                 `protobuf:"bytes,6,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Uuid          string                 `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Wwid          string                 `protobuf:"bytes,8,opt,name=wwid,proto3" json:"wwid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDevice) Reset() {
	*x = StorageDevice{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDevice) ProtoMessage() {}

func (x *StorageDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDevice.ProtoReflect.Descriptor instead.
func (*StorageDevice) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *StorageDevice) GetType() StorageType {
	if x != nil {
		return x.Type
	}
	return StorageType_Unknown
}

func (x *StorageDevice) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StorageDevice) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StorageDevice) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *StorageDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageDevice) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *StorageDevice) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StorageDevice) GetWwid() string {
	if x != nil {
		return x.Wwid
	}
	return ""
}

type StorageInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSize     uint64                 `protobuf:"varint,1,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	DeviceCount   uint32                 `protobuf:"varint,2,opt,name=device_count,json=deviceCount,proto3" json:"device_count,omitempty"`
	Devices       []*StorageDevice       `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageInformation) Reset() {
	*x = StorageInformation{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageInformation) ProtoMessage() {}

func (x *StorageInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageInformation.ProtoReflect.Descriptor instead.
func (*StorageInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *StorageInformation) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *StorageInformation) GetDeviceCount() uint32 {
	if x != nil {
		return x.DeviceCount
	}
	return 0
}

func (x *StorageInformation) GetDevices() []*StorageDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flags         string                 `protobuf:"bytes,3,opt,name=flags,proto3" json:"flags,omitempty"`
	Mtu           uint32                 `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Mac           string                 `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
	Addresses     []string               `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkInterface) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *NetworkInterface) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkInterface) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkInterface) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type NetworkInformation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterfaceCount uint32                 `protobuf:"varint,1,opt,name=interface_count,json=interfaceCount,proto3" json:"interface_count,omitempty"`
	Interfaces     []*NetworkInterface    `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkInformation) Reset() {
	*x = NetworkInformation{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInformation) ProtoMessage() {}

func (x *NetworkInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInformation.ProtoReflect.Descriptor instead.
func (*NetworkInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkInformation) GetInterfaceCount() uint32 {
	if x != nil {
		return x.InterfaceCount
	}
	return 0
}

func (x *NetworkInformation) GetInterfaces() []*NetworkInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type HardwareInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *SystemInformation     `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Compute       *ComputeInformation    `protobuf:"bytes,2,opt,name=compute,proto3" json:"compute,omitempty"`
	Memory        *MemoryInformation     `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       *StorageInformation    `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	Network       *NetworkInformation    `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInformation) Reset() {
	*x = HardwareInformation{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInformation) ProtoMessage() {}

func (x *HardwareInformation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInformation.ProtoReflect.Descriptor instead.
func (*HardwareInformation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *HardwareInformation) GetSystem() *SystemInformation {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *HardwareInformation) GetCompute() *ComputeInformation {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *HardwareInformation) GetMemory() *MemoryInformation {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *HardwareInformation) GetStorage() *StorageInformation {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *HardwareInformation) GetNetwork() *NetworkInformation {
	if x != nil {
		return x.Network
	}
	return nil
}

type CreateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hardware      *HardwareInformation   `protobuf:"bytes,1,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *CreateServerRequest) GetHardware() *HardwareInformation {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *CreateServerRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *Address) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wipe          bool                   `protobuf:"varint,1,opt,name=wipe,proto3" json:"wipe,omitempty"`
	InsecureWipe  bool                   `protobuf:"varint,2,opt,name=insecure_wipe,json=insecureWipe,proto3" json:"insecure_wipe,omitempty"`
	SetupBmc      bool                   `protobuf:"varint,3,opt,name=setup_bmc,json=setupBmc,proto3" json:"setup_bmc,omitempty"`
	RebootTimeout float64                `protobuf:"fixed64,4,opt,name=reboot_timeout,json=rebootTimeout,proto3" json:"reboot_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResponse.ProtoReflect.Descriptor instead.
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *CreateServerResponse) GetWipe() bool {
	if x != nil {
		return x.Wipe
	}
	return false
}

func (x *CreateServerResponse) GetInsecureWipe() bool {
	if x != nil {
		return x.InsecureWipe
	}
	return false
}

func (x *CreateServerResponse) GetSetupBmc() bool {
	if x != nil {
		return x.SetupBmc
	}
	return false
}

func (x *CreateServerResponse) GetRebootTimeout() float64 {
	if x != nil {
		return x.RebootTimeout
	}
	return 0
}

type MarkServerAsWipedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkServerAsWipedRequest) Reset() {
	*x = MarkServerAsWipedRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkServerAsWipedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkServerAsWipedRequest) ProtoMessage() {}

func (x *MarkServerAsWipedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkServerAsWipedRequest.ProtoReflect.Descriptor instead.
func (*MarkServerAsWipedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *MarkServerAsWipedRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type MarkServerAsWipedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkServerAsWipedResponse) Reset() {
	*x = MarkServerAsWipedResponse{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkServerAsWipedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkServerAsWipedResponse) ProtoMessage() {}

func (x *MarkServerAsWipedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkServerAsWipedResponse.ProtoReflect.Descriptor instead.
func (*MarkServerAsWipedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

type UpdateBMCInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BmcInfo       *BMCInfo               `protobuf:"bytes,2,opt,name=bmc_info,json=bmcInfo,proto3" json:"bmc_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBMCInfoRequest) Reset() {
	*x = UpdateBMCInfoRequest{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBMCInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBMCInfoRequest) ProtoMessage() {}

func (x *UpdateBMCInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBMCInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateBMCInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateBMCInfoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateBMCInfoRequest) GetBmcInfo() *BMCInfo {
	if x != nil {
		return x.BmcInfo
	}
	return nil
}

type UpdateBMCInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBMCInfoResponse) Reset() {
	*x = UpdateBMCInfoResponse{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBMCInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBMCInfoResponse) ProtoMessage() {}

func (x *UpdateBMCInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBMCInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateBMCInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

type ReconcileServerAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Address       []*Address             `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileServerAddressesRequest) Reset() {
	*x = ReconcileServerAddressesRequest{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileServerAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileServerAddressesRequest) ProtoMessage() {}

func (x *ReconcileServerAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileServerAddressesRequest.ProtoReflect.Descriptor instead.
func (*ReconcileServerAddressesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *ReconcileServerAddressesRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ReconcileServerAddressesRequest) GetAddress() []*Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type ReconcileServerAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileServerAddressesResponse) Reset() {
	*x = ReconcileServerAddressesResponse{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileServerAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileServerAddressesResponse) ProtoMessage() {}

func (x *ReconcileServerAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileServerAddressesResponse.ProtoReflect.Descriptor instead.
func (*ReconcileServerAddressesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\"U\n" +
	"\aBMCInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04pass\x18\x04 \x01(\tR\x04pass\"\xe4\x01\n" +
	"\x11SystemInformation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\"\n" +
	"\fmanufacturer\x18\x02 \x01(\tR\fmanufacturer\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12#\n" +
	"\rserial_number\x18\x05 \x01(\tR\fserialNumber\x12\x1d\n" +
	"\n" +
	"sku_number\x18\x06 \x01(\tR\tskuNumber\x12\x16\n" +
	"\x06family\x18\a \x01(\tR\x06family\"\xcf\x01\n" +
	"\tProcessor\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\rR\x05speed\x12\x1d\n" +
	"\n" +
	"core_count\x18\x05 \x01(\rR\tcoreCount\x12!\n" +
	"\fthread_count\x18\x06 \x01(\rR\vthreadCount\"\xc5\x01\n" +
	"\x12ComputeInformation\x12(\n" +
	"\x10total_core_count\x18\x01 \x01(\rR\x0etotalCoreCount\x12,\n" +
	"\x12total_thread_count\x18\x02 \x01(\rR\x10totalThreadCount\x12'\n" +
	"\x0fprocessor_count\x18\x03 \x01(\rR\x0eprocessorCount\x12.\n" +
	"\n" +
	"processors\x18\x04 \x03(\v2\x0e.api.ProcessorR\n" +
	"processors\"\xb8\x01\n" +
	"\fMemoryModule\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x05 \x01(\rR\x04size\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\rR\x05speed\"\x82\x01\n" +
	"\x11MemoryInformation\x12\x1d\n" +
	"\n" +
	"total_size\x18\x01 \x01(\rR\ttotalSize\x12!\n" +
	"\fmodule_count\x18\x02 \x01(\rR\vmoduleCount\x12+\n" +
	"\amodules\x18\x03 \x03(\v2\x11.api.MemoryModuleR\amodules\"\xd4\x01\n" +
	"\rStorageDevice\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.api.StorageTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\tR\x06serial\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1f\n" +
	"\vdevice_name\x18\x06 \x01(\tR\n" +
	"deviceName\x12\x12\n" +
	"\x04uuid\x18\a \x01(\tR\x04uuid\x12\x12\n" +
	"\x04wwid\x18\b \x01(\tR\x04wwid\"\x84\x01\n" +
	"\x12StorageInformation\x12\x1d\n" +
	"\n" +
	"total_size\x18\x01 \x01(\x04R\ttotalSize\x12!\n" +
	"\fdevice_count\x18\x02 \x01(\rR\vdeviceCount\x12,\n" +
	"\adevices\x18\x03 \x03(\v2\x12.api.StorageDeviceR\adevices\"\x94\x01\n" +
	"\x10NetworkInterface\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\tR\x05flags\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\rR\x03mtu\x12\x10\n" +
	"\x03mac\x18\x05 \x01(\tR\x03mac\x12\x1c\n" +
	"\taddresses\x18\x06 \x03(\tR\taddresses\"t\n" +
	"\x12NetworkInformation\x12'\n" +
	"\x0finterface_count\x18\x01 \x01(\rR\x0einterfaceCount\x125\n" +
	"\n" +
	"interfaces\x18\x02 \x03(\v2\x15.api.NetworkInterfaceR\n" +
	"interfaces\"\x8e\x02\n" +
	"\x13HardwareInformation\x12.\n" +
	"\x06system\x18\x01 \x01(\v2\x16.api.SystemInformationR\x06system\x121\n" +
	"\acompute\x18\x02 \x01(\v2\x17.api.ComputeInformationR\acompute\x12.\n" +
	"\x06memory\x18\x03 \x01(\v2\x16.api.MemoryInformationR\x06memory\x121\n" +
	"\astorage\x18\x04 \x01(\v2\x17.api.StorageInformationR\astorage\x121\n" +
	"\anetwork\x18\x05 \x01(\v2\x17.api.NetworkInformationR\anetwork\"g\n" +
	"\x13CreateServerRequest\x124\n" +
	"\bhardware\x18\x01 \x01(\v2\x18.api.HardwareInformationR\bhardware\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\"7\n" +
	"\aAddress\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x93\x01\n" +
	"\x14CreateServerResponse\x12\x12\n" +
	"\x04wipe\x18\x01 \x01(\bR\x04wipe\x12#\n" +
	"\rinsecure_wipe\x18\x02 \x01(\bR\finsecureWipe\x12\x1b\n" +
	"\tsetup_bmc\x18\x03 \x01(\bR\bsetupBmc\x12%\n" +
	"\x0ereboot_timeout\x18\x04 \x01(\x01R\rrebootTimeout\".\n" +
	"\x18MarkServerAsWipedRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"&\n" +
	"\x10HeartbeatRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x1b\n" +
	"\x19MarkServerAsWipedResponse\"\x13\n" +
	"\x11HeartbeatResponse\"S\n" +
	"\x14UpdateBMCInfoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12'\n" +
	"\bbmc_info\x18\x02 \x01(\v2\f.api.BMCInfoR\abmcInfo\"\x17\n" +
	"\x15UpdateBMCInfoResponse\"]\n" +
	"\x1fReconcileServerAddressesRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12&\n" +
	"\aaddress\x18\x02 \x03(\v2\f.api.AddressR\aaddress\"\"\n" +
	" ReconcileServerAddressesResponse*>\n" +
	"\vStorageType\x12\v\n" +
	"\aUnknown\x10\x00\x12\a\n" +
	"\x03SSD\x10\x01\x12\a\n" +
	"\x03HDD\x10\x02\x12\b\n" +
	"\x04NVMe\x10\x03\x12\x06\n" +
	"\x02SD\x10\x042\x8d\x03\n" +
	"\x05Agent\x12C\n" +
	"\fCreateServer\x12\x18.api.CreateServerRequest\x1a\x19.api.CreateServerResponse\x12R\n" +
	"\x11MarkServerAsWiped\x12\x1d.api.MarkServerAsWipedRequest\x1a\x1e.api.MarkServerAsWipedResponse\x12g\n" +
	"\x18ReconcileServerAddresses\x12$.api.ReconcileServerAddressesRequest\x1a%.api.ReconcileServerAddressesResponse\x12:\n" +
	"\tHeartbeat\x12\x15.api.HeartbeatRequest\x1a\x16.api.HeartbeatResponse\x12F\n" +
	"\rUpdateBMCInfo\x12\x19.api.UpdateBMCInfoRequest\x1a\x1a.api.UpdateBMCInfoResponseBLZJgithub.com/talos-systems/sidero/app/sidero-controller-manager/internal/apib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var (
	file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_api_proto_msgTypes  = make([]protoimpl.MessageInfo, 22)
	file_api_proto_goTypes   = []any{
		(StorageType)(0),                         // 0: api.StorageType
		(*BMCInfo)(nil),                          // 1: api.BMCInfo
		(*SystemInformation)(nil),                // 2: api.SystemInformation
		(*Processor)(nil),                        // 3: api.Processor
		(*ComputeInformation)(nil),               // 4: api.ComputeInformation
		(*MemoryModule)(nil),                     // 5: api.MemoryModule
		(*MemoryInformation)(nil),                // 6: api.MemoryInformation
		(*StorageDevice)(nil),                    // 7: api.StorageDevice
		(*StorageInformation)(nil),               // 8: api.StorageInformation
		(*NetworkInterface)(nil),                 // 9: api.NetworkInterface
		(*NetworkInformation)(nil),               // 10: api.NetworkInformation
		(*HardwareInformation)(nil),              // 11: api.HardwareInformation
		(*CreateServerRequest)(nil),              // 12: api.CreateServerRequest
		(*Address)(nil),                          // 13: api.Address
		(*CreateServerResponse)(nil),             // 14: api.CreateServerResponse
		(*MarkServerAsWipedRequest)(nil),         // 15: api.MarkServerAsWipedRequest
		(*HeartbeatRequest)(nil),                 // 16: api.HeartbeatRequest
		(*MarkServerAsWipedResponse)(nil),        // 17: api.MarkServerAsWipedResponse
		(*HeartbeatResponse)(nil),                // 18: api.HeartbeatResponse
		(*UpdateBMCInfoRequest)(nil),             // 19: api.UpdateBMCInfoRequest
		(*UpdateBMCInfoResponse)(nil),            // 20: api.UpdateBMCInfoResponse
		(*ReconcileServerAddressesRequest)(nil),  // 21: api.ReconcileServerAddressesRequest
		(*ReconcileServerAddressesResponse)(nil), // 22: api.ReconcileServerAddressesResponse
	}
)

var file_api_proto_depIdxs = []int32{
	3,  // 0: api.ComputeInformation.processors:type_name -> api.Processor
	5,  // 1: api.MemoryInformation.modules:type_name -> api.MemoryModule
	0,  // 2: api.StorageDevice.type:type_name -> api.StorageType
	7,  // 3: api.StorageInformation.devices:type_name -> api.StorageDevice
	9,  // 4: api.NetworkInformation.interfaces:type_name -> api.NetworkInterface
	2,  // 5: api.HardwareInformation.system:type_name -> api.SystemInformation
	4,  // 6: api.HardwareInformation.compute:type_name -> api.ComputeInformation
	6,  // 7: api.HardwareInformation.memory:type_name -> api.MemoryInformation
	8,  // 8: api.HardwareInformation.storage:type_name -> api.StorageInformation
	10, // 9: api.HardwareInformation.network:type_name -> api.NetworkInformation
	11, // 10: api.CreateServerRequest.hardware:type_name -> api.HardwareInformation
	1,  // 11: api.UpdateBMCInfoRequest.bmc_info:type_name -> api.BMCInfo
	13, // 12: api.ReconcileServerAddressesRequest.address:type_name -> api.Address
	12, // 13: api.Agent.CreateServer:input_type -> api.CreateServerRequest
	15, // 14: api.Agent.MarkServerAsWiped:input_type -> api.MarkServerAsWipedRequest
	21, // 15: api.Agent.ReconcileServerAddresses:input_type -> api.ReconcileServerAddressesRequest
	16, // 16: api.Agent.Heartbeat:input_type -> api.HeartbeatRequest
	19, // 17: api.Agent.UpdateBMCInfo:input_type -> api.UpdateBMCInfoRequest
	14, // 18: api.Agent.CreateServer:output_type -> api.CreateServerResponse
	17, // 19: api.Agent.MarkServerAsWiped:output_type -> api.MarkServerAsWipedResponse
	22, // 20: api.Agent.ReconcileServerAddresses:output_type -> api.ReconcileServerAddressesResponse
	18, // 21: api.Agent.Heartbeat:output_type -> api.HeartbeatResponse
	20, // 22: api.Agent.UpdateBMCInfo:output_type -> api.UpdateBMCInfoResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
