---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - setup-ci
    privileged: true
    resources:
      requests:
        cpu: 24000
        memory: 48GiB
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: lint-pull-request
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make lint
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-pull-request
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make REGISTRY=registry.dev.talos-systems.io PUSH=true
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: sfyra-pull-request
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make run-sfyra REGISTRY=registry.dev.talos-systems.io
    privileged: true
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_PASSWORD:
        from_secret: ghcr_token
    commands:
      - docker login --username "$${GHCR_USERNAME}" --password "$${GHCR_PASSWORD}" ghcr.io
      - make PUSH=true
    when:
      event:
        exclude:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: sfyra
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make run-sfyra
    privileged: true
    when:
      event:
        exclude:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-release
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make release
    when:
      event:
        - tag
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
        - sha512
      draft: true
      files:
        - _out/infrastructure-sidero/*/*
    when:
      event:
        - tag

volumes:
  - name: docker-socket
    temp: {}
  - name: outerdockersock
    host:
      path: /var/ci-docker
  - name: docker
    temp: {}
---
kind: pipeline
type: kubernetes
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
---
kind: signature
hmac: 6e8280c06e511ffeb8fb07e94c0920ffaa13ecaadba0dcba1b432b1351cc4d0a

...
