[build]
  base = "website"
  publish = "dist"
  command = "gridsome build"

[context.deploy-preview]
  base = "website"
  publish = "dist"
  command = "gridsome build"

[context.branch-deploy]
  base = "website"
  publish = "dist"
  command = "gridsome build"
