apiVersion: v1
kind: Service
metadata:
  name: metadata-server
  namespace: system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: server
    control-plane: metal-metadata-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-server
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      control-plane: metal-metadata-server
  template:
    metadata:
      labels:
        control-plane: metal-metadata-server
    spec:
      hostNetwork: ${SIDERO_METADATA_SERVER_HOST_NETWORK:=false}
      containers:
        - image: server:latest
          imagePullPolicy: Always
          args:
            - --port=${SIDERO_METADATA_SERVER_PORT:=8080}
          name: server
          ports:
            - containerPort: ${SIDERO_METADATA_SERVER_PORT:=8080}
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 10
