apiVersion: v1
kind: Service
metadata:
  name: tftp
  namespace: system
spec:
  ports:
    - port: 69
      targetPort: tftp
      protocol: UDP
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: ipxe
  namespace: system
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: system
spec:
  ports:
    - port: 50100
      targetPort: grpc
      protocol: TCP
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election=false
          image: controller:latest
          imagePullPolicy: Always
          name: manager
          ports:
            - name: tftp
              containerPort: 69
              protocol: UDP
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: grpc
              containerPort: 50100
              protocol: TCP
          env:
            - name: API_ENDPOINT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            limits:
              cpu: 250m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
