# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.6.9"

pre_release = false

preface = """\
"""

[notes]

[notes.talos]
    title = "Talos Linux"
        description = """\
Sidero Metal now supports Talos Linux v1.11.x.
"""
