# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "siderolabs/sidero"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.4.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.capi]
        title = "CAPI v1beta1"
        description = """\
This release of Sidero brings compatibility with CAPI v1beta1.
"""

    [notes.ipmi-pxe-method]
        title = "IPMI PXE Method"
        description = """\
IPMI PXE method (UEFI, BIOS) can now be configured with `SIDERO_CONTROLLER_MANAGER_IPMI_PXE_METHOD` while installing Sidero.
"""

    [notes.siderolink]
        title = "SideroLink"
        description = """\
Sidero now connects to all servers using SideroLink (available only with Talos >= 0.14).
This enables streaming of kernel logs and events back to Sidero.

All server logs can now be viewed by getting logs of one of the container of the `sidero-controller-manager`:

```
kubectl logs -f -n sidero-system deployment/sidero-controller-manager -c serverlogs
```

Events:

```
kubectl logs -f -n sidero-system deployment/sidero-controller-manager -c serverevents
```
"""

    [notes.addresses]
        title = "Machine Addresses"
        description = """\
Sidero now populates `MetalMachine` addresses with the ones discovered from Siderolink server events.
Which is then propagated to CAPI `Machine` resources.

Requires Talos >= v0.14.
"""

    [notes.conditions]
        title = "New `MetalMachines` Conditions"
        description = """\
New set of conditions is now available which can simplify cluster troubleshooting:

- `TalosConfigLoaded` is set to false when the config load has failed.
- `TalosConfigValidated` is set to false when the config validation
fails on the node.
- `TalosInstalled` is set to true/false when talos installer finishes.

Requires Talos >= v0.14.
"""

    [notes.pxeboot]
        title = "Retry PXE Boot"
        description = """\
Sidero server controller now keeps track of Talos installation progress.
Now the node will be PXE booted until Talos installation succeeds.
"""

    [notes.bootfromdisk]
        title = "iPXE Boot From Disk Method"
        description = """\
iPXE boot from disk method can now be set not only on the global level, but also in the Server and ServerClass specs.
"""

    [notes.clustertemplate]
        title = "Cluster Template"
        description = """\
Sidero ships with new cluster template without `init` nodes.
This template is only compatible with Talos >= 0.14 (it requires SideroLink feature which was introduced in Talos 0.14).

On upgrade, Sidero supports clusters running Talos < 0.14 if they were created before the upgrade.
Use [legacy template](https://github.com/talos-systems/sidero/blob/release-0.4/templates/cluster-template.yaml) to deploy clusters with Talos < 0.14.
"""
