apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: serverclass-sample
spec:
  qualifiers:
    cpu:
      - manufacturer: "Intel(R) Corporation"
        version: "Intel(R) Atom(TM) CPU C3558 @ 2.20GHz"
    systemInformation:
      - family: Unknown
        manufacturer: Unknown
        productName: Unknown
        serialNumber: Unknown
        skuNumber: Unknown
        version: Unknown
    labelSelectors:
      - key1: "val1"
      - key2: "val2"
    labelSelector:
      matchLabels:
        foo: bar
      matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
            - central
            - east
        - key: environment
          operator: NotIn
          values:
            - prod
