
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.arges.dev
  resources:
  - serverclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.arges.dev
  resources:
  - serverclasses/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.arges.dev
  resources:
  - servers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.arges.dev
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
