resources:
  - namespace.yaml

bases:
  - ../app/caps-controller-manager/config
  - ../app/sidero-controller-manager/config

commonLabels:
  app: sidero
  cluster.x-k8s.io/provider: 'sidero'
  cluster.x-k8s.io/v1alpha3: v1alpha3
